### PR TITLE
Added CI so I can get public docker images

### PR DESCRIPTION
**Pull request by toonsevrin**
I really needed those public docker images, so I've copied all the scripst over from the project referenced by @ibuildthecloud in #26.

I've got no experience with dapper/drone so hopefully it just works. Commits from maintainers are allowed.

### CODE REVIEW

**Comment by toonsevrin** [comment]
No worries, it's the least I can do to give something back!

**Comment by toonsevrin** [comment]
Little bump for this PR to not go stale :)

**Comment by toonsevrin** [comment]
Bump!

**Comment by brandond** [comment]
I'll take a look at this on Monday. The Drone runners are managed by a different team, so I will probably need their assistance to get this turned up.

**Comment by brandond** [comment]
@toonsevrin this is done, but master turned out to need another fix for connection pooling support in order to build properly. Also note that since this is configured as a static/nocgo build, sqlite support is not available so the kine docker images will require an external database.

**Comment by toonsevrin** [comment]
Oh, that sounds like something undesirable (not supporting sqlite), anyways, thanks for the merge, hopefully the builds will pass soon ;)

**Comment by toonsevrin** [comment]
Seems like images are not being published to docker hub, could this be added @brandond.

**Comment by rothgar** [comment]
I'm also hoping to get the official images pushed at some point.

**Comment by brandond** [comment]
@rothgar they should be out there now. We just haven't tagged many releases lately.

**Comment by rothgar** [comment]
I was hoping one could be manually built from an existing tag. There's nothing at https://hub.docker.com/r/rancher/kine and dockerhub is a bit of a mess to search because "kine" gets almost 800 other containers

**Pull request merged**
